### ISSUE TITLE
Старый API не работает

### ISSUE THREAD

**Issue by raitonoberu** [raitonoberu/ruobr_api#3]
Любой запрос к API падает с ошибкой 403 Forbidden:
<details>

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    ruobr.getUser()
  File "C:\Users\raitonoberu\ruobr_api\ruobr_api\__main__.py", line 81, in getUser
    user = self._get("user/")
  File "C:\Users\raitonoberu\ruobr_api\ruobr_api\__main__.py", line 56, in _get
    raise NoSuccessException(response.text)
ruobr_api.exceptions.NoSuccessException: <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
</details>

Похоже, официальная поддержка старого приложения "Дневник" окончательно прекращена, и они решили отключить API. Для нас это означает, что придётся мигрировать на API из нового приложения (#2), а там полно "ломающих изменений".

**Comment by raitonoberu** [comment]
2.0.0 работает на новом API.
